language: node_js

node_js:
  - node
  - lts/*

env:
  global:
    - CC_TEST_REPORTER_ID=b2cb5a2be8ff6aefd34d6dafdc9edece963888d60210aae8a6c1b79d2b86c4b5

before_script:
  - wget -O ./cctr https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  - chmod +x ./cctr
  - ./cctr before-build

after_script:
  - ./cctr after-build -t lcov --exit-code $TRAVIS_TEST_RESULT

jobs:
  include:
    - stage: deploy
      script: npm pack
      deploy:
        - provider: npm
          email: me@mgsisk.com
          api_key:
            secure: iZBAzpbIUpjziI+s/j5pT04biN9fBkmhTj0Sr2wDurka+iCsqNsgTSoHLHAczvsuZA1SFiU747wljZsgsL072aNyZN44uasQ/4FRY3ttAateT9MMnCZ3A9v7+0bo0Y1QkQRTMOiuNzZ7+LOf/r5Xeb0CWJ+N6C/WBIT/ny7nYoH9ahKbBjlvR0JHLXzWWVsdKe1n5gDOIwP88q0A9t2B+5EO80Y0IZ4exOfFL+52GZG0z3c7Fhvu9fI4J5Zypu39X9VwZORR9HJWAP/NsK74lwywEnO9oeQ3DLOCRrbkYenpCkFheX1HnFQ9eN6jkFDNykDDGxhTAuPKq0EoJPWbPFsqDWaeOGsOb0aMyt6WwyH8rtTpKOs3M/Ef0SE3OHZiOWbMpLchX5j682Wbd3M92Ht2W3gWaSsXHolOI12q1xeqWpCMv+JI0ufNdsqfCAt57DgeJqQYxF7F8Lj7ZLwGi4B2Oh9wmgeKIARbgoqaGbN6cV3vsGEuoe5ivvMzGM49S+2kPylklBxESFusmXSJoarsXdQ5cSOWO1bEBkLGZpjtnXHyIFD3QYxGIXo3jiFJYIXRLFGX67vH+6ioOYM6ikfUwcrEtikt0fsJQliNNz1ktzEvpOCKYnFpiJ4/s4hhZ4ZeOVFwPstsJaXZpLIt9+jo4Zwrz7BCvdyYe/DUZ5c=
          on:
            repo: mgsisk/remark-lint-config
            tags: true
        - provider: npm
          registry: https://npm.pkg.github.com
          email: me@mgsisk.com
          api_key:
            secure: NVuvoFIrS6eCjlbRtvz37BmqNLiZ2POehTtjwK9JEg+LdFNqSuYVpHN1VXELpAqJA95JCpL2//Nj6gEVjyVwtoiigqgv6JJlJe6WZinENoHV8mYb9OPDKy+b5pIkz0eEL0nf3gtKk0AydhP7ue5E1ptxiSqkcAr9njxjS1eNuW0FVp5ib9JdqqleIEEKfpJgLqGseju8xuHBXFZFmbwWGXmfF84rfwuEFfaoqpfW4wIV9zyeU6bMn/+ovcg6dQASGaXiUXVnOfNerXe9Pa1GnKU5nGCde4gMlti5RbUcvSu8GWYWbtd/NqvQij6Xmz2q2XE3wyMXJZUV5HamcXJG+e0R37JiS7mtMllrc6jbX18hljOaWji7BhHzmd+YsOHcuDjxbDEM0SVgZuhbLhghhE91HpLRhSVh3szseINiqzOTU91Oaf7iiB9qex6MmCX/h60TbmVfnjw+/gV144ZZ/2NHyCDNAL70qo62xMa1Pm1cG+psKEg1LbA2cvegOU883BpQKbwkfN/+imD9lR5gLRgR1byHtmWi2CnkUbwnY0VwFBdpppaEJBcfKENPSuYBpjDpf1+/hnqG0BALUZ75Z39GipnxDE/F2g7+dwTdqCnAC4qgXily6UQGGM7hRCgOQQC0zBS4ttuoxLB+5DG/9Wk7xK+UJ0C9CwanRHDIoGE=
          edge:
            branch: master
          on:
            repo: mgsisk/remark-lint-config
            tags: true
        - provider: releases
          skip_cleanup: true
          file_glob: true
          file: mgsisk-remark-lint-config-*.tgz
          api_key:
            secure: NVuvoFIrS6eCjlbRtvz37BmqNLiZ2POehTtjwK9JEg+LdFNqSuYVpHN1VXELpAqJA95JCpL2//Nj6gEVjyVwtoiigqgv6JJlJe6WZinENoHV8mYb9OPDKy+b5pIkz0eEL0nf3gtKk0AydhP7ue5E1ptxiSqkcAr9njxjS1eNuW0FVp5ib9JdqqleIEEKfpJgLqGseju8xuHBXFZFmbwWGXmfF84rfwuEFfaoqpfW4wIV9zyeU6bMn/+ovcg6dQASGaXiUXVnOfNerXe9Pa1GnKU5nGCde4gMlti5RbUcvSu8GWYWbtd/NqvQij6Xmz2q2XE3wyMXJZUV5HamcXJG+e0R37JiS7mtMllrc6jbX18hljOaWji7BhHzmd+YsOHcuDjxbDEM0SVgZuhbLhghhE91HpLRhSVh3szseINiqzOTU91Oaf7iiB9qex6MmCX/h60TbmVfnjw+/gV144ZZ/2NHyCDNAL70qo62xMa1Pm1cG+psKEg1LbA2cvegOU883BpQKbwkfN/+imD9lR5gLRgR1byHtmWi2CnkUbwnY0VwFBdpppaEJBcfKENPSuYBpjDpf1+/hnqG0BALUZ75Z39GipnxDE/F2g7+dwTdqCnAC4qgXily6UQGGM7hRCgOQQC0zBS4ttuoxLB+5DG/9Wk7xK+UJ0C9CwanRHDIoGE=
          on:
            repo: mgsisk/remark-lint-config
            tags: true
